CC     := gcc
CFLAGS := -Wall -Werror -g

SRCS   := client.c server.c clientmfs.c

OBJS   := ${SRCS:c=o}
PROGS  := ${SRCS:.c=}

.PHONY: all
all: ${PROGS}

${PROGS} : % : %.o Makefile.net
	${CC} $<  -g -o $@ udp.c -L. -lmfs

clean:
	rm -f ${PROGS} ${OBJS}

%.o: %.c Makefile
	${CC} ${CFLAGS} -c $<
